version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: todo_database
      POSTGRES_PASSWORD: user
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
